title: Codex
description: A library to write abstract interpreters in OCaml.
theme: just-the-docs
color_scheme: myscheme

url: https://codex-semantics-library.github.io

aux_links:
  Repository: https://github.com/codex-semantics-library/codex

logo: "/assets/codex.png"

nav_external_links:
  - title: Patricia Tree Library
    url: patricia-tree
    hide_icon: true # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
