title: Home of the Codex Semantics Library
description: A library to write abstract interpreters in OCaml.
theme: just-the-docs

url: https://codex-semantics-library.github.io

aux_links:
  Repository: https://github.com/codex-semantics-library/codex
