title: Codex
description: A library to write abstract interpreters in OCaml.
theme: just-the-docs
color_scheme: myscheme

url: https://codex-semantics-library.github.io

aux_links:
  '<i class="fab fa-github"></i> &nbsp; Repository': https://github.com/codex-semantics-library/codex

logo: "/assets/codex.png"

callouts:
  warning:
    title: Warning
    color: red
  note:
    color: blue

exclude: [
    Makefile,
    README.md,
    .sass-cache/,
    .jekyll-cache/,
    gemfiles/,
    Gemfile,
    Gemfile.lock
    node_modules/,
    vendor/bundle/,
    vendor/cache/,
    vendor/gems/,
    vendor/ruby/,
  ]

plugins:
  - jekyll-redirect-from
