title: Home of the Codex Semantics Library
description: A library to write abstract interpreters in OCaml.
theme: just-the-docs

url: https://codex-semantics-library.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
