# Ruby plugin for odoc generated json files (by dune build @doc-json)
# Autodectects json files placed in _data/api
# Originally written by Allan Blanchard for Frama-C's website
# https://git.frama-c.com/pub/pub.frama-c.com
#
# This expects you place files generated by 'dune build @doc-json'
# from '_build/default/_doc/_html/<package-name>' (note that this EXCLUDES the odoc package list page!)
# in '_data/api/<package-name>/'
#
# You also have to move the '_build/default/_doc/_html/<package-name>/db.js' file (generated by sherlodoc)
# to 'assets/js/db.<package-name>.js'
module OdocPlugin
  class OdocPageGenerator < Jekyll::Generator
    safe true

    def find_all_pages(hash)
      results = []
      def iter(hash, path, results, depth)
        if hash then
          hash.each do |key, value|
            if key.end_with? 'html' and value.is_a? Hash and value.key?("header") then
              results << [path, key[..-5].gsub("_", " "), value] # strip html from key
            elsif value.is_a? Hash
              npath = path + [key]
              iter(value, npath, results, depth+1)
            else
              raise "Don't know what to do with #{key} value #{value}\n"
            end
          end
        end
      end
      iter(hash, [], results, 0)
      results
    end

    def generate(site)
      pages = find_all_pages(site.data['api'])
      site.data["odoc_pages"] = []
      pages.each do |info|
        page = OdocPage.new(site, info[0], info[1], info[2])
        site.pages << page
        site.data["odoc_pages"] << page
      end
    end
  end

  class OdocPage < Jekyll::Page
    def initialize(site, path, name, data)
      @site = site
      @base = site.source
      @dir = "api/" + path.join('/')
      @basename = name
      @ext = '.html'
      @name = @basename + @ext
      # We can get package from the path thanks to the folder structure.
      # 'dune build @doc-json' generates a tree rooted at package:
      # (./package-name, ./package-name/module, ./package-name/index.html...)
      package = path[0]
      @data = {
        'odoc' => data,
        'layout' => 'odoc',
        'package' => package,
        'katex' => data["uses_katex"],
        'breadcrumbs' => false,
      }
      if path.length == 1 and name == "index" then
        @data['title'] = package
        @data['parent'] = 'API'
      else
        item = data["breadcrumbs"][-1]["name"]
        @data['title'] = item + " - " + package
        @data['nav_exclude'] = true
      end
    end
  end
end
